import type { Metadata } from "next";
import "../../globalsLanding.css";
import { Poppins } from "next/font/google";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "JejakStore | Auth",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin-ext"],
});

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();

  if (session && user.role === "CUSTOMER") {
    return redirect("/");
  }
  return <main className={`${poppins.className}`}>{children}</main>;
}
