import type { Metadata } from "next";
import "../../globalsLanding.css";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "JejakStore | Auth",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin-ext"],
});

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div className="flex min-h-screen w-full flex-col bg-muted/40">
    //   <Sidebar />
    //   <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
    //     <Header />
    <main className={`${poppins.className}`}>{children}</main>
    //   </div>
    // </div>
  );
}
