import type { Metadata } from "next";
import "../../globalsLanding.css";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "JejakStore",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin-ext"],
});

export default async function LandingRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className={`${poppins.className}`}>{children}</main>;
}
