import type { Metadata } from "next";
import "../../../globals.css";

export const metadata: Metadata = {
  title: "JejakStore | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-background text-foreground min-h-screen">{children}</div>
  );
}
