import type { Metadata } from "next";
import "../../../globals.css";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "JejakStore | Auth",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();

  if (session && user.role === "SUPERADMIN") {
    return redirect("/dashboard");
  }

  return (
    <div className="bg-background text-foreground min-h-screen">{children}</div>
  );
}
